### PR TITLE
Quiz Example

### PR DESCRIPTION
**Pull request by dbkeator**
Example quiz added to "quizes" folder, named according to the episode it corresponds to, and using the XML-Moodle format.  This example used questions in the challenge section of the episode.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@dbkeator where could I see the "result"?  I see no quizes at https://training.repronim.org/mod/resource/view.php?id=8

**Comment by dbkeator** [comment]
We haven't yet created the actual quiz.  You can see the imported questions here: https://training.repronim.org/question/edit.php?courseid=7&cat=10%2C56&category=10%2C56

**Comment by dbkeator** [comment]
P.S. will show at our 4pm wrap-up hangout...

**Comment by dbkeator** [comment]
@yarikoptic Ok, added sample quiz: https://training.repronim.org/course/view.php?id=7

**Pull request merged**
